volumes:
  pg_data:
  static:
  ssl_data:  # объём для SSL‑сертификатов

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/static

  frontend:
    build: ./frontend/
    command: sh -c "cp -r /app/build/. /app/static"
    volumes:
      - static:/app/static

  gateway:
    build: ./nginx/
    volumes:
      - static:/app/static
      - ./ssl-certs:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    ports:
      - 7000:80
