# Generated by Django 5.1.1 on 2026-06-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
