# Generated by Django 6.0.6 on 2026-06-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_customuser_favorite_recipes_favoriterecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(to='backend.tags', verbose_name='Тэги блюда'),
        ),
    ]
