# Generated by Django 6.0.6 on 2026-06-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_recipes_tags_recipes_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='title',
            new_name='name',
        ),
    ]
