# Generated by Django 6.0.6 on 2026-06-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_title_tags_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='unit_measurement',
            new_name='measurement_unit',
        ),
    ]
