# Generated by Django 6.0.6 on 2026-06-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_unit_measurement_ingredients_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='description',
            new_name='text',
        ),
    ]
