# Generated by Django 6.0.6 on 2026-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
