# Generated by Django 6.0.6 on 2026-06-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='title',
            new_name='name',
        ),
    ]
