# Generated by Django 6.0.6 on 2026-06-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_ingredients_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recipes')),
            ],
            options={
                'unique_together': {('code', 'recipe')},
            },
        ),
    ]
