# Generated by Django 6.0.6 on 2026-06-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_recipes_is_favorited_recipes_is_in_shopping_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='date_post',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_publisched',
        ),
    ]
