# Generated by Django 6.0.6 on 2026-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_recipes_date_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
