# Generated by Django 6.0.6 on 2026-06-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_recipes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.ingredients', verbose_name='Ингредиенты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.tags', verbose_name='Тэги блюда'),
            preserve_default=False,
        ),
    ]
