# Generated by Django 6.0.6 on 2026-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_ingredients_options_alter_recipes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='backend.recipes', verbose_name='Любимые рецепты'),
        ),
    ]
