# Generated by Django 6.0.6 on 2026-06-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_customuser_avatar_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
