# Generated by Django 6.0.6 on 2026-06-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_delete_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
