# Generated by Django 6.0.6 on 2026-06-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_ingredients_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
