# Generated by Django 6.0.6 on 2026-06-13 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_recipes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscripsions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_in_shopping_cart',
        ),
        migrations.CreateModel(
            name='UserRecipesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_shopping_cart', models.BooleanField(default=False)),
                ('is_favorited', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
