# Generated by Django 6.0.6 on 2026-06-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_subscripsions_remove_recipes_is_favorited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.TextField(),
        ),
    ]
