# Generated by Django 6.0.6 on 2026-06-15 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_recipes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSuscriptionsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recipes')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscripsions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='usersuscriptionssettings',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersuscriptionssettings',
            unique_together={('subscriber', 'creator')},
        ),
    ]
