# Generated by Django 6.0.6 on 2026-06-15 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_usersuscriptionssettings_delete_subscripsions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuscriptionssettings',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_as_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersuscriptionssettings',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_as_subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
