# Generated by Django 6.0.6 on 2026-06-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_usersuscriptionssettings_creator_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSuscriptionsSettings',
            new_name='UserSubscriptionsSettings',
        ),
    ]
