# Generated by Django 6.0.6 on 2026-06-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_usersuscriptionssettings_usersubscriptionssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(),
        ),
    ]
