# Generated by Django 6.0.6 on 2026-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_customuser_avatar_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/'),
            preserve_default=False,
        ),
    ]
