user nginx;
events { worker_connections 1024; }
worker_processes auto;
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server {
        listen 80;
    	server_name tyter.3utilities.com;

        location /api/ {
            proxy_set_header Host $http_host;
            proxy_pass http://backend:7000/api/;
        }

        location /admin/ {
            proxy_set_header Host $http_host;
            proxy_pass http://backend:7000/admin/;
        }

        location /media/ {
            alias /media/;
        }

        location /static/ {
           alias /app/static/static/;
        }

        location / {
            root /app/static/;
            try_files $uri $uri/ /index.html;
        }
    }
}
